import type { Metadata } from "next";
import "./globals.css";
import { NotesContextProvider } from "./context/notesStore";
import { MyProvider } from "./context/store";
import { ToastProvider } from "@/components/ToastProvider";



export const metadata: Metadata = {
  title: "NoteVault",
  description: "Generated by NoteVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
        
          <NotesContextProvider>
            <MyProvider>
            {children}
            <ToastProvider/>
            </MyProvider>
          </NotesContextProvider>
        
        </body>
    </html>
  );
}
