import type { Metadata } from "next";
import "../globals.css";
import {ToastProvider} from "../../components/ToastProvider";



export const metadata: Metadata = {
  title: "NoteVault",
  description: "Generated by NoteVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
         <div>
         {children}
         <ToastProvider />
         </div>
        </body>
    </html>
  );
}
