import type { Metadata } from "next";
import "../globals.css";
import { MyProvider } from "../context/store";



export const metadata: Metadata = {
  title: "NoteVault",
  description: "Generated by NoteVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
        <MyProvider>
          {children}
        </MyProvider>
        </body>
    </html>
  );
}
